language: python

sudo: required

python:
  - "2.7"

install:
  # - pip install -r requirements.txt --quiet
  - pip install -r requirements.txt

script:
  - sudo -E env "PATH=$PATH" bash ./script/t -vv

# after_success:
#   - pip install python-coveralls && coveralls
