language: python

python:
  - "2.7"

install:
  # - pip install -r requirements.txt --quiet
  - pip install -r requirements.txt

script:
  - bash ./script/t -vv

# after_success:
#   - pip install python-coveralls && coveralls
